### ISSUE TITLE
Joystick Up and Down controls reversed

### ISSUE THREAD

**Issue by DRok17** [Comet-Games/Worlds-Hardest-Game-Vita#2]
Up is down and down is up on 1.10. Dpad is fine.

**Comment by Comet-Games** [comment]
I am working on this ready for the next update

**Comment by Comet-Games** [comment]
I think i have fixed the issue but i will have to test first, if anyone has tested the newest version could you put the result here please?

**Comment by Comet-Games** [comment]
Fixed!
